spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:mysql://localhost:3306/gestione_teatri?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: pass1
    driver-class-name: com.mysql.cj.jdbc.Driver
  